
source 'https://github.com/pengwenxin/CGSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CGAuthorKit_Category_Example' do
  pod 'CGAuthorKit_Category', :path => '../'

  target 'CGAuthorKit_Category_Tests' do
    inherit! :search_paths

    
  end
end
